version: '3.8'

services:
  db:
    image: postgres:15
    container_name: rona-finance-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finanzas
    ports:
      - "5433:5432" # Usamos el 5433 en el host para no chocar con el otro postgres que tienes corriendo en el 5432
    volumes:
      - rona_pgdata:/var/lib/postgresql/data

volumes:
  rona_pgdata:
